"use client";

import React, { useState } from "react";
import {
  Check,
  AlertCircle,
  AlertTriangle,
  HelpCircle,
  Layers,
  Sparkles,
  Info,
  ChevronDown,
  ChevronUp,
  Tag,
} from "lucide-react";
import { ColumnDetectionResult, DetectedColumn } from "@/lib/types";

interface ColumnDetectorProps {
  detectionResult: ColumnDetectionResult;
  rawHeaders: string[];
}

export const ColumnDetector: React.FC<ColumnDetectorProps> = ({
  detectionResult,
  rawHeaders,
}) => {
  const [showMappingDetails, setShowMappingDetails] = useState(false);

  const { detected, missingRequired, extraHeaders, hasAutoGeneratedCode } = detectionResult;

  // Primary standard columns ordered by priority
  const primaryOrder: DetectedColumn["key"][] = [
    "cpse_name",
    "material_code",
    "material_description",
    "specification",
    "unit",
  ];

  const primaryColumns = primaryOrder
    .map((key) => detected.find((c) => c.key === key))
    .filter((c): c is DetectedColumn => c !== undefined);

  const secondaryColumns = detected.filter(
    (c) => !primaryOrder.includes(c.key) && c.isDetected
  );

  return (
    <div className="bg-white rounded-2xl border border-slate-200 p-5 sm:p-6 shadow-xs space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-100">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center font-bold">
            <Layers className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900">Detected Columns</h3>
            <p className="text-xs text-slate-500">
              Automated schema mapping and field validation
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={() => setShowMappingDetails(!showMappingDetails)}
          className="text-xs text-indigo-600 hover:text-indigo-800 font-semibold flex items-center gap-1 self-start sm:self-center transition-colors cursor-pointer"
        >
          <span>{showMappingDetails ? "Hide Mapping Details" : "View Field Mappings"}</span>
          {showMappingDetails ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
        </button>
      </div>

      {/* Critical Warnings if Required Fields Missing */}
      {missingRequired.length > 0 && (
        <div className="p-4 rounded-xl bg-rose-50 border border-rose-200 text-rose-900 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-rose-600 shrink-0 mt-0.5" />
          <div className="space-y-1 text-xs">
            <h4 className="font-bold text-sm text-rose-800">Missing Mandatory Columns</h4>
            <p className="text-rose-700 leading-relaxed">
              The uploaded file does not contain:{" "}
              <strong>{missingRequired.map((c) => c.label).join(", ")}</strong>.
              Material standardization requires at least raw item descriptions to operate.
            </p>
          </div>
        </div>
      )}

      {/* Notice if Material Code is Missing and Temporary IDs will be generated */}
      {hasAutoGeneratedCode && (
        <div className="p-3.5 rounded-xl bg-amber-50/80 border border-amber-200 text-amber-900 flex items-start gap-2.5 text-xs">
          <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
          <div>
            <span className="font-bold">Auto-Generated Material Codes: </span>
            <span className="text-amber-800">
              No material code column was found. Temporary IDs (e.g. <code>TMP-01001</code>) will be created automatically for tracking.
            </span>
          </div>
        </div>
      )}

      {/* Badges Grid for Detected Standard Columns */}
      <div className="space-y-2">
        <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block">
          Core Harmonization Attributes
        </span>

        <div className="flex flex-wrap gap-2.5">
          {primaryColumns.map((col) => {
            if (col.isDetected) {
              return (
                <div
                  key={col.key}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-emerald-50 text-emerald-800 border border-emerald-200 shadow-2xs hover:bg-emerald-100/70 transition-colors"
                  title={`Mapped from: "${col.originalHeader}"${col.sampleValue ? ` | Sample: "${col.sampleValue}"` : ""}`}
                >
                  <span className="w-4 h-4 rounded-full bg-emerald-500 text-white flex items-center justify-center shrink-0">
                    <Check className="w-3 h-3 stroke-[3]" />
                  </span>
                  <span>{col.label}</span>
                  {col.originalHeader && col.originalHeader.toLowerCase() !== col.label.toLowerCase() && (
                    <span className="text-[10px] text-emerald-600 font-mono font-normal">
                      ({col.originalHeader})
                    </span>
                  )}
                </div>
              );
            }

            // Not detected
            if (col.key === "material_code") {
              return (
                <div
                  key={col.key}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-amber-50 text-amber-800 border border-amber-200 shadow-2xs"
                  title="Auto-generated temporary IDs will be assigned"
                >
                  <span className="w-4 h-4 rounded-full bg-amber-500 text-white flex items-center justify-center shrink-0">
                    <Sparkles className="w-2.5 h-2.5" />
                  </span>
                  <span>{col.label} (Auto-Generated)</span>
                </div>
              );
            }

            return (
              <div
                key={col.key}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold ${
                  col.isRequired
                    ? "bg-rose-50 text-rose-800 border border-rose-200"
                    : "bg-slate-100 text-slate-500 border border-slate-200"
                }`}
                title={col.isRequired ? "Required field is missing" : "Optional field not found"}
              >
                <span
                  className={`w-4 h-4 rounded-full flex items-center justify-center shrink-0 text-white ${
                    col.isRequired ? "bg-rose-500" : "bg-slate-400"
                  }`}
                >
                  ×
                </span>
                <span>{col.label}</span>
                {col.isRequired && <span className="text-[10px] text-rose-600 uppercase font-bold">(Required)</span>}
              </div>
            );
          })}
        </div>
      </div>

      {/* Secondary Extra Detected Columns */}
      {secondaryColumns.length > 0 && (
        <div className="space-y-2 pt-2 border-t border-slate-100">
          <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block">
            Additional Detected Metadata
          </span>
          <div className="flex flex-wrap gap-2">
            {secondaryColumns.map((col) => (
              <div
                key={col.key}
                className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium bg-slate-50 text-slate-700 border border-slate-200"
                title={`Mapped from: "${col.originalHeader}"`}
              >
                <Tag className="w-3 h-3 text-indigo-500" />
                <span>{col.label}</span>
                {col.originalHeader && (
                  <span className="text-[10px] text-slate-500 font-mono">
                    ({col.originalHeader})
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Detailed Mapping Table (Collapsible) */}
      {showMappingDetails && (
        <div className="pt-3 border-t border-slate-100 space-y-3 animate-in fade-in">
          <h4 className="text-xs font-bold uppercase tracking-wider text-slate-600 flex items-center gap-1.5">
            <Info className="w-3.5 h-3.5 text-indigo-600" />
            <span>Field Mapping Matrix & Sample Values</span>
          </h4>

          <div className="overflow-x-auto border border-slate-200 rounded-xl bg-slate-50/50">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-100/80 text-slate-700 font-semibold border-b border-slate-200">
                <tr>
                  <th className="py-2 px-3">Standard Field</th>
                  <th className="py-2 px-3">Matched Header</th>
                  <th className="py-2 px-3">Requirement</th>
                  <th className="py-2 px-3">Sample Value</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white font-medium">
                {detected.map((col) => (
                  <tr key={col.key} className="hover:bg-slate-50/80">
                    <td className="py-2 px-3 font-semibold text-slate-900">{col.label}</td>
                    <td className="py-2 px-3 font-mono text-slate-700">
                      {col.originalHeader ? (
                        <span className="px-1.5 py-0.5 rounded bg-slate-100 text-slate-800 border border-slate-200">
                          {col.originalHeader}
                        </span>
                      ) : (
                        <span className="text-slate-400 italic">None</span>
                      )}
                    </td>
                    <td className="py-2 px-3">
                      {col.isRequired ? (
                        <span className="text-rose-600 font-bold">Mandatory</span>
                      ) : (
                        <span className="text-slate-500">Optional</span>
                      )}
                    </td>
                    <td className="py-2 px-3 text-slate-600 truncate max-w-xs">
                      {col.sampleValue || "—"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {extraHeaders.length > 0 && (
            <div className="text-[11px] text-slate-500">
              <strong className="font-semibold text-slate-700">Unmapped Headers: </strong>
              {extraHeaders.map((h) => `"${h}"`).join(", ")} (Stored as raw attributes)
            </div>
          )}
        </div>
      )}
    </div>
  );
};
