import { MaterialRecord, CPSEProfile, DataQualityStats, AuditLog, PipelineStage } from "./types";

export const CPSE_PROFILES: CPSEProfile[] = [
  {
    id: "ONGC",
    name: "Oil and Natural Gas Corporation",
    ministry: "Ministry of Petroleum and Natural Gas",
    totalRecords: 48920,
    cleanedPercentage: 94.2,
    prefixCode: "ONG",
    color: "text-amber-700 dark:text-amber-300",
    bgLight: "bg-amber-50 dark:bg-amber-950/40 border-amber-200 dark:border-amber-800",
    badgeBorder: "border-amber-300 bg-amber-50 text-amber-900",
  },
  {
    id: "BHEL",
    name: "Bharat Heavy Electricals Limited",
    ministry: "Ministry of Heavy Industries",
    totalRecords: 38450,
    cleanedPercentage: 91.8,
    prefixCode: "BHL",
    color: "text-blue-700 dark:text-blue-300",
    bgLight: "bg-blue-50 dark:bg-blue-950/40 border-blue-200 dark:border-blue-800",
    badgeBorder: "border-blue-300 bg-blue-50 text-blue-900",
  },
  {
    id: "NTPC",
    name: "NTPC Limited",
    ministry: "Ministry of Power",
    totalRecords: 32100,
    cleanedPercentage: 89.4,
    prefixCode: "NTP",
    color: "text-emerald-700 dark:text-emerald-300",
    bgLight: "bg-emerald-50 dark:bg-emerald-950/40 border-emerald-200 dark:border-emerald-800",
    badgeBorder: "border-emerald-300 bg-emerald-50 text-emerald-900",
  },
  {
    id: "IOCL",
    name: "Indian Oil Corporation Limited",
    ministry: "Ministry of Petroleum and Natural Gas",
    totalRecords: 29800,
    cleanedPercentage: 93.1,
    prefixCode: "IOC",
    color: "text-orange-700 dark:text-orange-300",
    bgLight: "bg-orange-50 dark:bg-orange-950/40 border-orange-200 dark:border-orange-800",
    badgeBorder: "border-orange-300 bg-orange-50 text-orange-900",
  },
  {
    id: "SAIL",
    name: "Steel Authority of India Limited",
    ministry: "Ministry of Steel",
    totalRecords: 24650,
    cleanedPercentage: 87.5,
    prefixCode: "SAIL",
    color: "text-indigo-700 dark:text-indigo-300",
    bgLight: "bg-indigo-50 dark:bg-indigo-950/40 border-indigo-200 dark:border-indigo-800",
    badgeBorder: "border-indigo-300 bg-indigo-50 text-indigo-900",
  },
  {
    id: "GAIL",
    name: "GAIL (India) Limited",
    ministry: "Ministry of Petroleum and Natural Gas",
    totalRecords: 18400,
    cleanedPercentage: 95.0,
    prefixCode: "GAL",
    color: "text-cyan-700 dark:text-cyan-300",
    bgLight: "bg-cyan-50 dark:bg-cyan-950/40 border-cyan-200 dark:border-cyan-800",
    badgeBorder: "border-cyan-300 bg-cyan-50 text-cyan-900",
  },
  {
    id: "CIL",
    name: "Coal India Limited",
    ministry: "Ministry of Coal",
    totalRecords: 15600,
    cleanedPercentage: 86.2,
    prefixCode: "CIL",
    color: "text-slate-700 dark:text-slate-300",
    bgLight: "bg-slate-100 dark:bg-slate-800/40 border-slate-300 dark:border-slate-700",
    badgeBorder: "border-slate-300 bg-slate-100 text-slate-800",
  },
];

export const INITIAL_DATA_QUALITY_STATS: DataQualityStats = {
  totalRecords: 148920,
  recordsProcessed: 132450,
  successfullyCleaned: 121800,
  pendingReview: 10650,
  rejectedRecords: 2100,
  abbreviationsExpanded: 42390,
  unitsStandardized: 28140,
  formattingFixed: 19820,
  manualReviewRequired: 8.1,
  accuracyRate: 91.9,
};

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: "upload",
    stepNumber: 1,
    title: "Data Upload",
    subtitle: "Multi-CPSE Ingestion",
    status: "active",
    description: "Accepts CSV/Excel data sheets with ERP material dumps across CPSEs (SAP, Oracle, Maximo).",
    iconName: "UploadCloud",
    badgeText: "Ready",
  },
  {
    id: "cleaning",
    stepNumber: 2,
    title: "Data Cleaning",
    subtitle: "Active Module",
    status: "active",
    description: "Industrial abbreviation expansion, SI unit standardization, delimiter parsing, and whitespace normalization.",
    estimatedAccuracy: "96.4%",
    iconName: "Sparkles",
    badgeText: "Active Pipeline",
  },
  {
    id: "attribute_extraction",
    stepNumber: 3,
    title: "Attribute Extraction",
    subtitle: "AI Token Extraction",
    status: "coming_soon",
    description: "Future NER/LLM module extracting key material specs (Material Grade, Nominal Size, Pressure Class, Rating, Standard).",
    iconName: "FileSearch",
    badgeText: "Coming Soon",
  },
  {
    id: "embedding_generation",
    stepNumber: 4,
    title: "Embedding Generation",
    subtitle: "Dense Vectorization",
    status: "future",
    description: "Future domain-specific BERT / text-embedding-3 model to produce high-dimensional semantic representations.",
    iconName: "Cpu",
    badgeText: "Future Phase",
  },
  {
    id: "ai_matching",
    stepNumber: 5,
    title: "AI Material Matching",
    subtitle: "Cosine Similarity & Deduplication",
    status: "coming_soon",
    description: "Future pgvector nearest-neighbor search to detect identical cross-CPSE items despite distinct legacy descriptions.",
    iconName: "Network",
    badgeText: "Coming Soon",
  },
  {
    id: "national_code_mapping",
    stepNumber: 6,
    title: "National Material Code",
    subtitle: "UNSPSC / Harmonized Scheme",
    status: "future",
    description: "Assigns a Unified National Material Master Code (UNMC) for centralized public procurement and inventory sharing.",
    iconName: "CheckCircle2",
    badgeText: "Future Phase",
  },
];

export const MOCK_MATERIALS: MaterialRecord[] = [
  {
    id: "MAT-001",
    materialCode: "ONG-1001",
    cpse: "ONGC",
    rawDescription: "SS HEX BOLT M10X50 MM WITH NUT & 2 WSHR",
    cleanedDescription: "Stainless Steel Hexagonal Bolt M10 x 50 mm with Nut and 2 Washer",
    category: "Fasteners & Hardware",
    subCategory: "Bolts & Nuts",
    status: "cleaned",
    confidenceScore: 98,
    standardUnit: "Nos",
    rawUnit: "NOS.",
    abbreviationsFound: ["SS → Stainless Steel", "HEX → Hexagonal", "WSHR → Washer"],
    issuesDetected: ["Multiple abbreviations", "Non-standard delimiter", "Unit case"],
    attributes: { Material: "Stainless Steel", Shape: "Hexagonal", Size: "M10 x 50 mm", Includes: "Nut + 2 Washers" },
    nationalMaterialCode: "IN-NMC-31161501",
    createdAt: "2026-09-08T09:30:00Z",
    updatedAt: "2026-09-08T10:15:00Z",
  },
  {
    id: "MAT-002",
    materialCode: "BHL-2001",
    cpse: "BHEL",
    rawDescription: "STAINLESS STEEL HEXAGONAL BOLT M10 X 50MM GRADE 316",
    cleanedDescription: "Stainless Steel Hexagonal Bolt M10 x 50 mm Grade 316",
    category: "Fasteners & Hardware",
    subCategory: "Bolts & Nuts",
    status: "cleaned",
    confidenceScore: 97,
    standardUnit: "Nos",
    rawUnit: "PCS",
    abbreviationsFound: ["MM → mm"],
    issuesDetected: ["Merged unit notation (50MM)"],
    attributes: { Material: "Stainless Steel 316", Shape: "Hexagonal", Size: "M10 x 50 mm" },
    nationalMaterialCode: "IN-NMC-31161501",
    createdAt: "2026-09-08T09:35:00Z",
    updatedAt: "2026-09-08T10:16:00Z",
  },
  {
    id: "MAT-003",
    materialCode: "NTP-4402",
    cpse: "NTPC",
    rawDescription: "CS FLG WNRF 150# 4\" SCH 40 ASTM A105",
    cleanedDescription: "Carbon Steel Flange Weld Neck Raised Face Class 150 4 inch Schedule 40 ASTM A105",
    category: "Piping & Piping Components",
    subCategory: "Flanges",
    status: "cleaned",
    confidenceScore: 96,
    standardUnit: "Nos",
    rawUnit: "NO",
    abbreviationsFound: ["CS → Carbon Steel", "FLG → Flange", "WNRF → Weld Neck Raised Face", "150# → Class 150", "SCH → Schedule"],
    issuesDetected: ["Compound abbreviations", "Pound sign for pressure class", "Inch symbol quotation"],
    attributes: { Material: "Carbon Steel ASTM A105", Type: "Weld Neck Raised Face", Rating: "Class 150", Size: "4 inch", Schedule: "40" },
    nationalMaterialCode: "IN-NMC-40141602",
    createdAt: "2026-09-08T08:12:00Z",
    updatedAt: "2026-09-08T08:45:00Z",
  },
  {
    id: "MAT-004",
    materialCode: "IOC-7719",
    cpse: "IOCL",
    rawDescription: "CARBON STEEL WELD NECK FLANGE 4 INCH 150 LBS SCH40 A105N",
    cleanedDescription: "Carbon Steel Weld Neck Flange 4 inch Class 150 Schedule 40 A105N",
    category: "Piping & Piping Components",
    subCategory: "Flanges",
    status: "cleaned",
    confidenceScore: 95,
    standardUnit: "Nos",
    rawUnit: "EA",
    abbreviationsFound: ["150 LBS → Class 150", "SCH40 → Schedule 40"],
    issuesDetected: ["Legacy LBS pressure unit"],
    attributes: { Material: "Carbon Steel A105N", Type: "Weld Neck", Rating: "Class 150", Size: "4 inch", Schedule: "40" },
    nationalMaterialCode: "IN-NMC-40141602",
    createdAt: "2026-09-08T07:40:00Z",
    updatedAt: "2026-09-08T08:10:00Z",
  },
  {
    id: "MAT-005",
    materialCode: "ONG-3312",
    cpse: "ONGC",
    rawDescription: "BALL VLV 2\" 300# FLGD END BODY A216 WCB TRIM SS316",
    cleanedDescription: "Ball Valve 2 inch Class 300 Flanged End Body A216 WCB Trim Stainless Steel 316",
    category: "Valves & Flow Control",
    subCategory: "Ball Valves",
    status: "cleaned",
    confidenceScore: 94,
    standardUnit: "Nos",
    rawUnit: "NOS",
    abbreviationsFound: ["VLV → Valve", "300# → Class 300", "FLGD → Flanged", "SS316 → Stainless Steel 316"],
    issuesDetected: ["Special characters", "Missing delimiter between rating and end connection"],
    attributes: { Type: "Ball Valve", Size: "2 inch", Rating: "Class 300", Body: "A216 WCB", Trim: "SS316" },
    nationalMaterialCode: "IN-NMC-40141608",
    createdAt: "2026-09-08T11:00:00Z",
    updatedAt: "2026-09-08T11:20:00Z",
  },
  {
    id: "MAT-006",
    materialCode: "SAIL-9011",
    cpse: "SAIL",
    rawDescription: "MS PLT 25MM THK IS 2062 E250 BR 2500X10000MM",
    cleanedDescription: "Mild Steel Plate 25 mm Thickness IS 2062 E250 BR 2500 x 10000 mm",
    category: "Structural Steel & Metals",
    subCategory: "Plates",
    status: "cleaned",
    confidenceScore: 96,
    standardUnit: "MT",
    rawUnit: "TON",
    abbreviationsFound: ["MS → Mild Steel", "PLT → Plate", "THK → Thickness", "MM → mm"],
    issuesDetected: ["Imperial to Metric unit conversion pending", "Merged dimensions"],
    attributes: { Material: "Mild Steel IS 2062 E250 BR", Thickness: "25 mm", Width: "2500 mm", Length: "10000 mm" },
    nationalMaterialCode: "IN-NMC-30101804",
    createdAt: "2026-09-08T06:15:00Z",
    updatedAt: "2026-09-08T06:50:00Z",
  },
  {
    id: "MAT-007",
    materialCode: "GAL-5020",
    cpse: "GAIL",
    rawDescription: "SPIRAL WOUND GASK 3\" 600# ASME B16.20 HOOPOUTERING SS316",
    cleanedDescription: "Spiral Wound Gasket 3 inch Class 600 ASME B16.20 Hoop Outer Ring Stainless Steel 316",
    category: "Gaskets & Seals",
    subCategory: "Spiral Wound Gaskets",
    status: "cleaned",
    confidenceScore: 92,
    standardUnit: "Nos",
    rawUnit: "NOS",
    abbreviationsFound: ["GASK → Gasket", "600# → Class 600", "SS316 → Stainless Steel 316"],
    issuesDetected: ["Concatenated compound word (HOOPOUTERING)"],
    attributes: { Standard: "ASME B16.20", Rating: "Class 600", Size: "3 inch", Material: "SS316 Ring" },
    nationalMaterialCode: "IN-NMC-31401509",
    createdAt: "2026-09-08T10:05:00Z",
    updatedAt: "2026-09-08T10:25:00Z",
  },
  {
    id: "MAT-008",
    materialCode: "ONG-9921",
    cpse: "ONGC",
    rawDescription: "PIPE SMLS CS 6\" SCH 80 ASTM A106 GR.B BEV END",
    cleanedDescription: "Pipe Seamless Carbon Steel 6 inch Schedule 80 ASTM A106 Grade B Beveled End",
    category: "Piping & Piping Components",
    subCategory: "Seamless Pipes",
    status: "pending_review",
    confidenceScore: 84,
    standardUnit: "m",
    rawUnit: "MTR",
    abbreviationsFound: ["SMLS → Seamless", "CS → Carbon Steel", "SCH → Schedule", "BEV → Beveled", "GR.B → Grade B"],
    issuesDetected: ["Ambiguous wall thickness grade", "Manual verification recommended"],
    createdAt: "2026-09-08T11:45:00Z",
    updatedAt: "2026-09-08T11:45:00Z",
    reviewNote: "Confirm if A106 Grade B requires NACE MR0175 sour service compliance flag.",
  },
  {
    id: "MAT-009",
    materialCode: "BHL-8842",
    cpse: "BHEL",
    rawDescription: "COPPER CABLE 4CX16 SQMM XLPE/PVC/SWA/PVC 1.1KV ARMOURED",
    cleanedDescription: "Copper Cable 4 Core x 16 sq mm XLPE / PVC / SWA / PVC 1.1 kV Armoured",
    category: "Electrical & Instrumentation",
    subCategory: "Power Cables",
    status: "pending_review",
    confidenceScore: 81,
    standardUnit: "m",
    rawUnit: "MTRS",
    abbreviationsFound: ["SQMM → sq mm", "1.1KV → 1.1 kV", "4CX16 → 4 Core x 16"],
    issuesDetected: ["Multiple insulation abbreviations", "Complex cable layering sequence"],
    createdAt: "2026-09-08T12:05:00Z",
    updatedAt: "2026-09-08T12:05:00Z",
    reviewNote: "Verify standard Indian IS 7098 part 1 designation mapping.",
  },
  {
    id: "MAT-010",
    materialCode: "CIL-1104",
    cpse: "CIL",
    rawDescription: "IND MOTOR 55KW 415V 3PH 50HZ 1480RPM FOOT MTD FRAME 250M",
    cleanedDescription: "Induction Motor 55 kW 415 V 3 Phase 50 Hz 1480 rpm Foot Mounted Frame 250M",
    category: "Electrical & Instrumentation",
    subCategory: "Electric Motors",
    status: "pending_review",
    confidenceScore: 86,
    standardUnit: "Nos",
    rawUnit: "SET",
    abbreviationsFound: ["IND → Induction", "KW → kW", "V → V", "3PH → 3 Phase", "HZ → Hz", "RPM → rpm", "MTD → Mounted"],
    issuesDetected: ["Dense abbreviation cluster", "Multi-parameter electrical spec"],
    createdAt: "2026-09-08T12:15:00Z",
    updatedAt: "2026-09-08T12:15:00Z",
    reviewNote: "Check IE3 efficiency class parameter before approval.",
  },
  {
    id: "MAT-011",
    materialCode: "NTP-6031",
    cpse: "NTPC",
    rawDescription: "TEMP GAUGE 0-200 DEGC DIAL 150MM SS CASE BOTTOM CONN 1/2\" NPT",
    cleanedDescription: "Temperature Gauge 0-200 °C Dial 150 mm Stainless Steel Case Bottom Connection 1/2 inch NPT",
    category: "Electrical & Instrumentation",
    subCategory: "Sensors & Gauges",
    status: "approved",
    confidenceScore: 96,
    standardUnit: "Nos",
    rawUnit: "NOS",
    abbreviationsFound: ["TEMP → Temperature", "DEGC → °C", "MM → mm", "SS → Stainless Steel", "CONN → Connection"],
    issuesDetected: ["Unit standardization applied", "Abbreviation expanded"],
    nationalMaterialCode: "IN-NMC-41112214",
    reviewedBy: "S. Sharma (NTPC Chief Material Manager)",
    createdAt: "2026-09-07T14:20:00Z",
    updatedAt: "2026-09-08T09:10:00Z",
  },
  {
    id: "MAT-012",
    materialCode: "IOC-1099",
    cpse: "IOCL",
    rawDescription: "GLOBE VLV 50MM CL800 FORGED STEEL A105 SW END OS&Y BB",
    cleanedDescription: "Globe Valve 50 mm Class 800 Forged Steel A105 Socket Weld End Outside Screw and Yoke Bolted Bonnet",
    category: "Valves & Flow Control",
    subCategory: "Globe Valves",
    status: "approved",
    confidenceScore: 97,
    standardUnit: "Nos",
    rawUnit: "NOS",
    abbreviationsFound: ["VLV → Valve", "CL800 → Class 800", "SW → Socket Weld", "OS&Y → Outside Screw and Yoke", "BB → Bolted Bonnet"],
    issuesDetected: ["Complex valve construction abbreviations"],
    nationalMaterialCode: "IN-NMC-40141612",
    reviewedBy: "R. Verma (IOCL Materials Div)",
    createdAt: "2026-09-07T11:00:00Z",
    updatedAt: "2026-09-08T08:30:00Z",
  },
  {
    id: "MAT-013",
    materialCode: "ONG-8810",
    cpse: "ONGC",
    rawDescription: "UNKNOWN MISC SPARE PART OLD DWG 4022A",
    cleanedDescription: "Unknown Miscellaneous Spare Part Old Drawing 4022A",
    category: "General",
    subCategory: "Uncategorized",
    status: "rejected",
    confidenceScore: 42,
    standardUnit: "Nos",
    rawUnit: "NOS",
    abbreviationsFound: ["MISC → Miscellaneous", "DWG → Drawing"],
    issuesDetected: ["Insufficient descriptive attributes", "No dimensional specs", "Vague OEM drawing reference"],
    createdAt: "2026-09-07T16:00:00Z",
    updatedAt: "2026-09-08T07:15:00Z",
    reviewNote: "Rejected due to lack of material specification. Re-upload with full datasheet from ONGC ERP.",
  },
  {
    id: "MAT-014",
    materialCode: "SAIL-3392",
    cpse: "SAIL",
    rawDescription: "TEST RECORD INVALID DATA STRING ### ???",
    cleanedDescription: "Test Record Invalid Data String",
    category: "General",
    subCategory: "Uncategorized",
    status: "rejected",
    confidenceScore: 31,
    standardUnit: "Nos",
    rawUnit: "N/A",
    abbreviationsFound: [],
    issuesDetected: ["Corrupted data noise", "Missing all critical fields"],
    createdAt: "2026-09-07T17:30:00Z",
    updatedAt: "2026-09-08T07:18:00Z",
    reviewNote: "Corrupted ERP test entry rejected automatically.",
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "LOG-1001",
    timestamp: "2026-09-08T12:15:22Z",
    actor: "AutoCleaningWorker-3",
    action: "BATCH_STANDARDIZE",
    cpse: "ONGC",
    materialCode: "ONG-1001",
    details: "Expanded 3 abbreviations (SS, HEX, WSHR) and standardized unit (NOS -> Nos).",
    status: "success",
    ruleApplied: "Rule-EXP-ABBR-04, Rule-UNIT-SI-01",
  },
  {
    id: "LOG-1002",
    timestamp: "2026-09-08T12:05:40Z",
    actor: "AutoCleaningWorker-1",
    action: "BATCH_STANDARDIZE",
    cpse: "BHEL",
    materialCode: "BHL-2001",
    details: "Standardized compound unit notation '50MM' to '50 mm'. Confidence: 97%.",
    status: "success",
    ruleApplied: "Rule-SPACING-02",
  },
  {
    id: "LOG-1003",
    timestamp: "2026-09-08T11:45:10Z",
    actor: "QualityAuditService",
    action: "FLAG_FOR_REVIEW",
    cpse: "ONGC",
    materialCode: "ONG-9921",
    details: "Low confidence on wall thickness spec for seamless pipe. Flagged for engineer review.",
    status: "warning",
    ruleApplied: "Rule-CONF-THRESH-85",
  },
  {
    id: "LOG-1004",
    timestamp: "2026-09-08T10:15:30Z",
    actor: "S. Sharma (NTPC)",
    action: "APPROVE_RECORD",
    cpse: "NTPC",
    materialCode: "NTP-6031",
    details: "Manual review verified. Assigned National Material Master Code IN-NMC-41112214.",
    status: "success",
  },
  {
    id: "LOG-1005",
    timestamp: "2026-09-08T09:40:15Z",
    actor: "DataIngestionPipeline",
    action: "DATASET_UPLOAD",
    cpse: "IOCL",
    materialCode: "BATCH-IOC-2026-09",
    details: "Ingested 1,250 raw material items from SAP ECC dump. 1,180 matched parsing schema.",
    status: "info",
  },
  {
    id: "LOG-1006",
    timestamp: "2026-09-08T07:18:00Z",
    actor: "QualityAuditService",
    action: "AUTO_REJECT",
    cpse: "SAIL",
    materialCode: "SAIL-3392",
    details: "Record contained corrupted noise characters without recognizable attributes.",
    status: "error",
    ruleApplied: "Rule-DATA-INTEGRITY-01",
  },
];

export const MOCK_PROCESSING_STATS_BY_CPSE = [
  { cpse: "ONGC", raw: 48920, cleaned: 46080, pending: 2340, rejected: 500 },
  { cpse: "BHEL", raw: 38450, cleaned: 35300, pending: 2650, rejected: 500 },
  { cpse: "NTPC", raw: 32100, cleaned: 28700, pending: 2900, rejected: 500 },
  { cpse: "IOCL", raw: 29800, cleaned: 27750, pending: 1750, rejected: 300 },
  { cpse: "SAIL", raw: 24650, cleaned: 21570, pending: 2780, rejected: 300 },
  { cpse: "GAIL", raw: 18400, cleaned: 17480, pending: 820, rejected: 100 },
];

export const MOCK_CATEGORY_DISTRIBUTION = [
  { name: "Piping & Flanges", value: 35, count: 52120, color: "#2563eb" },
  { name: "Fasteners & Hardware", value: 25, count: 37230, color: "#3b82f6" },
  { name: "Valves & Flow Control", value: 18, count: 26800, color: "#60a5fa" },
  { name: "Electrical & Instruments", value: 12, count: 17870, color: "#93c5fd" },
  { name: "Structural Steel", value: 7, count: 10420, color: "#cbd5e1" },
  { name: "Others & Gaskets", value: 3, count: 4480, color: "#e2e8f0" },
];
