export type CPSE = "ONGC" | "BHEL" | "NTPC" | "IOCL" | "SAIL" | "GAIL" | "CIL";

export type ProcessingStatus = "raw" | "cleaned" | "pending_review" | "approved" | "rejected";

export interface MaterialRecord {
  id: string;
  materialCode: string;
  cpse: CPSE;
  rawDescription: string;
  cleanedDescription: string;
  category: string;
  subCategory?: string;
  status: ProcessingStatus;
  confidenceScore: number;
  standardUnit: string;
  rawUnit?: string;
  abbreviationsFound: string[];
  issuesDetected: string[];
  attributes?: Record<string, string>;
  nationalMaterialCode?: string;
  createdAt: string;
  updatedAt: string;
  reviewedBy?: string;
  reviewNote?: string;
}

export interface CPSEProfile {
  id: CPSE;
  name: string;
  ministry: string;
  totalRecords: number;
  cleanedPercentage: number;
  prefixCode: string;
  color: string;
  bgLight: string;
  badgeBorder: string;
}

export interface DataQualityStats {
  totalRecords: number;
  recordsProcessed: number;
  successfullyCleaned: number;
  pendingReview: number;
  rejectedRecords: number;
  abbreviationsExpanded: number;
  unitsStandardized: number;
  formattingFixed: number;
  manualReviewRequired: number;
  accuracyRate: number;
}

export interface AuditLog {
  id: string;
  timestamp: string;
  actor: string;
  action: string;
  cpse: CPSE | "SYSTEM";
  materialCode: string;
  details: string;
  status: "success" | "warning" | "info" | "error";
  ruleApplied?: string;
}

export interface PipelineStage {
  id: string;
  stepNumber: number;
  title: string;
  subtitle: string;
  status: "active" | "coming_soon" | "future";
  description: string;
  estimatedAccuracy?: string;
  iconName: string;
  badgeText: string;
}

export type UploadValidationStatus = "idle" | "validating" | "valid" | "warning" | "error";

export interface DetectedColumn {
  key: "cpse_name" | "material_code" | "material_description" | "specification" | "unit" | "category" | "plant";
  label: string;
  originalHeader: string | null;
  isRequired: boolean;
  isDetected: boolean;
  sampleValue?: string;
  description: string;
}

export interface ColumnDetectionResult {
  detected: DetectedColumn[];
  missingRequired: DetectedColumn[];
  extraHeaders: string[];
  totalHeaders: number;
  hasAutoGeneratedCode: boolean;
}

export interface StandardizedUploadRecord {
  id: string;
  rowIndex: number;
  cpse: string;
  materialCode: string;
  materialDescription: string;
  specification: string;
  unit: string;
  rawRow: Record<string, any>;
  hasMissingFields: boolean;
  missingFieldNames: string[];
  isCodeAutoGenerated?: boolean;
}

export interface DatasetSummaryStats {
  totalRecords: number;
  totalColumns: number;
  cpseCount: number;
  cpseList: string[];
  missingValuesCount: number;
  dataQualityScore: number;
  emptyFieldPercentage: number;
}

export interface ParsedDataset {
  id: string;
  fileName: string;
  fileSize: number;
  fileSizeBytesFormatted: string;
  fileType: "CSV" | "XLSX" | "XLS" | "TSV" | "UNKNOWN";
  rawHeaders: string[];
  records: StandardizedUploadRecord[];
  columnDetection: ColumnDetectionResult;
  summary: DatasetSummaryStats;
  validationStatus: UploadValidationStatus;
  validationErrors: string[];
  validationWarnings: string[];
  uploadedAt: string;
}

// ============================================================================
// Data Cleaning & Standardization Engine Types (FastAPI Integration)
// ============================================================================

export interface BackendHealthResponse {
  status: "healthy" | "unhealthy";
  service: string;
  version: string;
  timestamp: string;
  latencyMs?: number;
}

export interface BackendMaterialResponse {
  raw_description: string;
  cleaned_description: string;
  changes: string[];
  processing_status: "success" | "error" | "skipped";
}

export interface BackendCSVProcessSummary {
  total_rows: number;
  processed_rows: number;
  success_count: number;
  error_count: number;
  detected_description_column: string;
  processing_time_ms: number;
}

export interface BackendCSVProcessResponse {
  summary: BackendCSVProcessSummary;
  records: Array<Record<string, any>>;
}

export interface CleanedMaterialItem {
  id: string;
  materialCode: string;
  cpse: string;
  rawDescription: string;
  cleanedDescription: string;
  changesMade: string[];
  processingStatus: "Cleaned Successfully" | "Requires Review" | "Unchanged" | "Processing Error";
  isModified: boolean;
  requiresReview: boolean;
  category?: string;
  unit?: string;
  rawRow: Record<string, any>;
}

export interface CleaningBatchMetrics {
  totalRecords: number;
  successfullyCleaned: number;
  recordsModified: number;
  recordsRequiringReview: number;
  successRate: number;
  modifiedRate: number;
  reviewRate: number;
  processingTimeMs: number;
  detectedDescriptionColumn: string;
  sourceFileName: string;
  sourceCPSE?: string;
  processedAt: string;
  isFallbackMode?: boolean;
}

export interface CleaningStoreState {
  id: string;
  datasetName: string;
  metrics: CleaningBatchMetrics;
  items: CleanedMaterialItem[];
  rawRecordsCount: number;
  processedAt: string;
  status: "idle" | "processing" | "completed" | "error";
  errorMessage?: string;
}

